from __future__ import annotations

from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from doc_parsing.application.logging import get_logger
from doc_parsing.domain import PdfParser, PdfParserConfig, PdfParserFactory


class MockConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    kind: Literal["mock"] = Field(default="mock")


class MockPdfParser(PdfParser):
    def parse(self, file_path: Path) -> str:
        logger = get_logger(__name__, parser="mock")
        logger.info("mock.parse.start", extra={"path": str(file_path)})
        return (
            f"# Parsed {file_path.name}\n\n"
            "This output was generated by the mock parser."
        )


class MockPdfParserFactory(PdfParserFactory):
    config_model = MockConfig

    def create(self, config: PdfParserConfig) -> PdfParser:
        return MockPdfParser()
